pipeline {
    agent any
    tools {
       maven 'Maven3'
       jdk 'JDK17'
	}
    environment {
        APP_PORT = '9090'
    }
    stages {
        stage('Build') {
            steps {
		dir('jenkins-task1') {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
        stage('Unit Test') {
            steps {
		dir('jenkins-task1'){
                sh 'mvn test'
		}
            }
        }
    }
}
