pipeline {
    agent any
    tools {
	Maven3
	}
    environment {
        APP_PORT = '9090'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Unit Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
